language: node_js
node_js:
  - "8"
  
sudo: false

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - "hiptest-publisher -c cucumber-js.conf --token=$SECRET_TOKEN --only=features,step_definitions --test-run-id=16534"
  - npm install

script:
  - node_modules/.bin/cucumber-js --format=json | node_modules/cucumber-junit/bin/cucumber-junit --features-as-suites > junit_output.xml

after_script:
  - hiptest-publisher -c cucumber-js.conf --token=$SECRET_TOKEN --push=junit_output.xml --test-run-id=16534
  - |
     curl -X POST https://hiptest-pth.ngrok.io/connect/rest/api/results \
      -H 'authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI0OTYxMjc4Yi0yNTM3LTMwYjEtYTU3MC00OGEwZWIzNWQ2N2QiLCJjb250ZXh0Ijp7InByb2plY3RfaWQiOiIxMDAxMCIsInJlcG9zaXRvcnlfbmFtZSI6IlBoaWxUaG9tMjUvaHBzLWN1Y3VtYmVyLXJ1YnkifX0.pwop-TBdcLupmF7XfQRX6U8zKApqFjVFWPHunqWjlKE' \
      -H 'content-type: multipart/form-data' \
      -F results_file=@results.json
